apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: chatorbit-prod
  labels:
    app: chatorbit
    component: auth
spec:
  selector:
    app: chatorbit
    component: auth
  ports:
    - port: 8089
      targetPort: 8089
      name: http
  type: LoadBalancer