apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: chatorbit-prod
  labels:
    app: chatorbit
    component: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatorbit
      component: auth
  template:
    metadata:
      labels:
        app: chatorbit
        component: auth
    spec:
      containers:
        - name: auth-service
          image: celesteyang/auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
          env:
            - name: PORT
              value: "8089"
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: chatorbit-config
                  key: MONGO_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chatorbit-secrets
                  key: JWT_SECRET
            - name: LOGGING_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: chatorbit-config
                  key: LOGGING_LEVEL
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: chatorbit-config
                  key: ENVIRONMENT
          readinessProbe:
            tcpSocket:
              port: 8089
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8089
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
