apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: chatorbit-prod
  labels:
    app: chatorbit
    component: chat
spec:
  selector:
    app: chatorbit
    component: chat
  ports:
    - port: 8088
      targetPort: 8088
      name: http
  type: ClusterIP