apiVersion: v1
kind: ConfigMap
metadata:
  name: chatorbit-config
  namespace: chatorbit-prod
data:
  MONGO_URL: mongodb://mongo:27017
  REDIS_ADDR: redis:6379
  LOGGING_LEVEL: info
  ENVIRONMENT: production