apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: chatorbit-prod
  labels:
    app: chatorbit
    component: redis
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    app: chatorbit
    component: redis